site_name: YT Tech Wiki
site_url: https://Pluto-Yt.github.io/
site_author: Pluto-Yt
# Repository
repo_name: Pluto-Yt lab
repo_url: https://github.com/Pluto-Yt
edit_uri: docs

nav:
  - 关于我们: index.md
  - 技术文档: 
    - 数仓理论: 
        数仓理论: 技术文档/数仓理论.md  
    - MySQL:
        MySQL基础篇: 技术文档/SQL基础.md
        MySQL高级篇: 技术文档/SQL进阶.md
    - Hadoop: 
        Hadoop: 技术文档/Hadoop.md  
    - Hive:
        Hive: 技术文档/Hive.md
    - Spark:
        Spark: 技术文档/Spark.md
    - Flink:
        Flink: 技术文档/Flink.md
    - Kafka:
        Kafka: 技术文档/Kafka.md
    - Python:
        Python: 技术文档/Python.md
  # - 实习项目总结: 
  #     新客爆品: 
      
theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/library

  features:
    - navigation.tabs
    - navigation.top

  palette:
    
    # Light mode
    - blue: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
